Fix #147: encode subdir as a valid git ref format if needed

diff --git a/lib/git-subrepo b/lib/git-subrepo
--- a/lib/git-subrepo
+++ b/lib/git-subrepo
@@ -97,6 +97,7 @@ main() {
   local branch_first_commit=    # Return value from prepare_merge_base
 
   local subdir=                 # Subdirectory of the subrepo being used
+  local subdir_ref_enc=         # Valid git ref format of subdir
   local gitrepo=                # Path to .gitrepo file
 
   local original_head_commit=   # HEAD commit id at start of command
@@ -258,10 +259,10 @@ command:branch() {
   fi
 
   if $force_wanted; then
-    FAIL=false RUN git branch -D "subrepo/$subdir"
+    FAIL=false RUN git branch -D "subrepo/$subdir_ref_enc"
   fi
 
-  local branch="subrepo/$subdir"
+  local branch="subrepo/$subdir_ref_enc"
   if git:branch-exists "$branch"; then
     error "Branch '$branch' already exists. Use '--force' to override."
   fi
@@ -288,7 +289,7 @@ command:commit() {
   upstream_head_commit="$(git rev-parse "$refs_subrepo_fetch")"
 
   [[ -n $subrepo_commit_ref ]] ||
-    subrepo_commit_ref="subrepo/$subdir"
+    subrepo_commit_ref="subrepo/$subdir_ref_enc"
   subrepo:commit
 
   say "Subrepo commit '$subrepo_commit_ref' committed as"
@@ -317,10 +318,10 @@ command:status() {
 status-refs() {
   local output=
   while read line; do
-    [[ $line =~ ^([0-9a-f]+)\ refs/subrepo/$subdir/([a-z]+) ]] || continue
+    [[ $line =~ ^([0-9a-f]+)\ refs/subrepo/$subdir_ref_enc/([a-z]+) ]] || continue
     local sha1=; sha1="$(git rev-parse --short "${BASH_REMATCH[1]}")"
     local type="${BASH_REMATCH[2]}"
-    local ref="refs/subrepo/$subdir/$type"
+    local ref="refs/subrepo/$subdir_ref_enc/$type"
     if [[ $type == branch ]]; then
       output+="    Branch Ref:    $sha1 ($ref)"$'\n'
     elif [[ $type == commit ]]; then
@@ -463,7 +464,7 @@ subrepo:clone() {
 
 # Init a new subrepo from current repo:
 subrepo:init() {
-  local branch_name="subrepo/${subdir:??}"
+  local branch_name="subrepo/${subdir_ref_enc:??}"
   # Check if subdir is proper candidate for this init:
   assert-subdir-ready-for-init
 
@@ -490,9 +491,9 @@ subrepo:init() {
   RUN git branch "$branch_name"
 
   if [[ $subrepo_remote != none ]]; then
-    o "Create subrepo remote 'subrepo/$subdir' -> '$subrepo_remote'."
-    FAIL=false RUN git remote remove "subrepo/$subdir"
-    RUN git remote add "subrepo/$subdir" "$subrepo_remote"
+    o "Create subrepo remote 'subrepo/$subdir_ref_enc' -> '$subrepo_remote'."
+    FAIL=false RUN git remote remove "subrepo/$subdir_ref_enc"
+    RUN git remote add "subrepo/$subdir_ref_enc" "$subrepo_remote"
   fi
 
   o "Reset to the commit we started at."
@@ -524,7 +525,7 @@ subrepo:pull() {
     OK=false; CODE=-1; return
   fi
 
-  local branch_name="subrepo/$subdir"
+  local branch_name="subrepo/$subdir_ref_enc"
   if git:branch-exists "$branch_name"; then
     o "Deleting old '$branch_name' branch."
     RUN git branch -D "$branch_name"
@@ -715,14 +716,14 @@ subrepo:fetch() {
   OUT=true RUN git rev-parse FETCH_HEAD^0
   upstream_head_commit="$output"
 
-  local output=; output=$(git config "remote.subrepo/$subdir.url" || true)
+  local output=; output=$(git config "remote.subrepo/$subdir_ref_enc.url" || true)
   if [[ -z $output ]]; then
-    o "Create subrepo remote 'subrepo/$subdir' -> '$subrepo_remote'."
-    RUN git remote add "subrepo/$subdir" "$subrepo_remote"
+    o "Create subrepo remote 'subrepo/$subdir_ref_enc' -> '$subrepo_remote'."
+    RUN git remote add "subrepo/$subdir_ref_enc" "$subrepo_remote"
   else
     if [[ $output != $subrepo_remote ]]; then
-      o "Change subrepo remote 'subrepo/$subdir' -> '$subrepo_remote'."
-      git remote set-url "subrepo/$subdir" "$subrepo_remote"
+      o "Change subrepo remote 'subrepo/$subdir_ref_enc' -> '$subrepo_remote'."
+      git remote set-url "subrepo/$subdir_ref_enc" "$subrepo_remote"
     fi
   fi
 
@@ -732,7 +733,7 @@ subrepo:fetch() {
 
 # Create a subrepo branch containing all changes
 subrepo:branch() {
-  local branch="${1:-"subrepo/$subdir"}"
+  local branch="${1:-"subrepo/$subdir_ref_enc"}"
   o "Check if the '$branch' branch already exists."
   git:branch-exists "$branch" && return
 
@@ -879,6 +880,7 @@ subrepo:status() {
   for subdir in "${subrepos[@]}"; do
     subdir="${subdir#./}"
     subdir="${subdir%/}"
+    encode-subdir
 
     if [[ ! -f $subdir/.gitrepo ]]; then
       echo "'$subdir' is not a subrepo"
@@ -886,7 +888,7 @@ subrepo:status() {
       continue
     fi
 
-    refs_subrepo_fetch="refs/subrepo/$subdir/fetch"
+    refs_subrepo_fetch="refs/subrepo/$subdir_ref_enc/fetch"
     upstream_head_commit="$(
       git rev-parse --short "$refs_subrepo_fetch" 2> /dev/null || true
     )"
@@ -904,12 +906,12 @@ subrepo:status() {
     fi
 
     echo "Git subrepo '$subdir':"
-    git:branch-exists "subrepo/$subdir" &&
-      echo "  Subrepo Branch:  subrepo/$subdir"
-    local remote="subrepo/$subdir"
+    git:branch-exists "subrepo/$subdir_ref_enc" &&
+      echo "  Subrepo Branch:  subrepo/$subdir_ref_enc"
+    local remote="subrepo/$subdir_ref_enc"
     FAIL=false OUT=true RUN git config "remote.$remote.url"
     [[ -n $output ]] &&
-      echo "  Remote Name:     subrepo/$subdir"
+      echo "  Remote Name:     subrepo/$subdir_ref_enc"
     echo "  Remote URL:      $subrepo_remote"
     [[ -n $upstream_head_commit ]] &&
       echo "  Upstream Ref:    $upstream_head_commit"
@@ -944,7 +946,7 @@ subrepo:clean() {
     fi
   done
 
-  local remote="subrepo/$subdir"
+  local remote="subrepo/$subdir_ref_enc"
   FAIL=false OUT=true RUN git config "remote.$remote.url"
   if [[ -n $output ]]; then
     o "Remove remote '$remote'."
@@ -957,7 +959,7 @@ subrepo:clean() {
     if "$all_wanted"; then
       RUN rm -fr .git/refs/subrepo/
     else
-      RUN rm -fr .git/refs/subrepo/$subdir/
+      RUN rm -fr .git/refs/subrepo/$subdir_ref_enc/
     fi
   fi
 }
@@ -1143,13 +1145,14 @@ command-setup() {
     usage-error "The subdir '$subdir' should not be absolute path."
   subdir="${subdir#./}"
   subdir="${subdir%/}"
+  encode-subdir
 
   # Set refs_ variables:
-  refs_subrepo_branch="refs/subrepo/$subdir/branch"
-  refs_subrepo_commit="refs/subrepo/$subdir/commit"
-  refs_subrepo_fetch="refs/subrepo/$subdir/fetch"
-  refs_subrepo_pull="refs/subrepo/$subdir/pull"
-  refs_subrepo_push="refs/subrepo/$subdir/push"
+  refs_subrepo_branch="refs/subrepo/$subdir_ref_enc/branch"
+  refs_subrepo_commit="refs/subrepo/$subdir_ref_enc/commit"
+  refs_subrepo_fetch="refs/subrepo/$subdir_ref_enc/fetch"
+  refs_subrepo_pull="refs/subrepo/$subdir_ref_enc/pull"
+  refs_subrepo_push="refs/subrepo/$subdir_ref_enc/push"
 
   # Read/parse the .gitrepo file (unless clone; doesn't exist yet)
   gitrepo="$subdir/.gitrepo"
@@ -1201,6 +1204,76 @@ guess-subdir() {
   [[ $dir =~ ^[-a-zA-Z0-9]+$ ]] ||
     error "Can't determine subdir from '$subrepo_remote'."
   subdir="$dir"
+  encode-subdir
+}
+
+# Encode the subdir as a valid git ref format
+encode-subdir() {
+  subdir_ref_enc=$subdir
+  if [[ ! $subdir ]] || git check-ref-format "subrepo/$subdir"; then
+    return
+  fi
+
+  ## 0. escape %
+  subdir_ref_enc=${subdir_ref_enc//%/%25}
+
+  ## 1. They can include slash / for hierarchical (directory) grouping,
+  ##    but no slash-separated component can begin with a dot .  or
+  ##    end with the sequence .lock.
+  subdir_ref_enc=/$subdir_ref_enc/
+  subdir_ref_enc=${subdir_ref_enc//\/.//%2e}
+  subdir_ref_enc=${subdir_ref_enc//.lock\//%2elock/}
+  subdir_ref_enc=${subdir_ref_enc#/}
+  subdir_ref_enc=${subdir_ref_enc%/}
+
+  ## 2. They must contain at least one /.
+  ##    'subrepo/' be will prefixed, so this is always true.
+  ## 3. They cannot have two consecutive dots ..  anywhere.
+  subdir_ref_enc=${subdir_ref_enc//../%2e%2e}
+  subdir_ref_enc=${subdir_ref_enc//%2e./%2e%2e}
+  subdir_ref_enc=${subdir_ref_enc//.%2e/%2e%2e}
+
+  ## 4. They cannot have ASCII control characters
+  ##    (i.e. bytes whose values are lower than \040, or \177 DEL), space,
+  ##    tilde ~, caret ^, or colon : anywhere.
+  ## 5. They cannot have question-mark ?, asterisk *,
+  ##    or open bracket [ anywhere.
+  local i
+  local x
+  for (( i = 0; i < 32; ++i )); do
+    x=$(printf "%02x" $i)
+    subdir_ref_enc=${subdir_ref_enc//$(printf "%b" "\x$x")/%$x}
+  done
+  subdir_ref_enc=${subdir_ref_enc//$'\177'/%7f}
+  subdir_ref_enc=${subdir_ref_enc// /%20}
+  subdir_ref_enc=${subdir_ref_enc//\~/%7e}
+  subdir_ref_enc=${subdir_ref_enc//^/%5e}
+  subdir_ref_enc=${subdir_ref_enc//:/%3a}
+  subdir_ref_enc=${subdir_ref_enc//\?/%3f}
+  subdir_ref_enc=${subdir_ref_enc//\*/%2a}
+  subdir_ref_enc=${subdir_ref_enc//\[/%5b}
+  subdir_ref_enc=${subdir_ref_enc//$'\n'/%0a}
+
+  ## 6. They cannot begin or end with a slash / or contain multiple
+  ##    consecutive slashes. This rule is not revertable.
+  subdir_ref_enc=$(sed 's,^/\+\|/\+$,,g' <<< "$subdir_ref_enc")
+
+  ## 7. They cannot end with a dot ..
+  case "$subdir_ref_enc" in
+  *.) subdir_ref_enc=${subdir_ref_enc%.}
+      subdir_ref_enc+=%2e
+      ;;
+  esac
+
+  ## 8. They cannot contain a sequence @\{.
+  ## 9. They cannot be the single character @. always true
+  subdir_ref_enc=${subdir_ref_enc//@\{/%40\{}
+
+  ## 10. They cannot contain a \.
+  subdir_ref_enc=${subdir_ref_enc//\\/%5c}
+
+  subdir_ref_enc=$(git check-ref-format --normalize --allow-onelevel "$subdir_ref_enc") ||
+    error "Can't determine valid subdir_ref_enc from '$subdir'."
 }
 
 #------------------------------------------------------------------------------
